[settings]
quiet = true
task_output = "interleave"

[tools]
zig = "0.16.0"
bats = "1.14.0"
jq = "1.8.2"
coreutils = "0.12.0"

[tasks.build]
run = "zig build"

[tasks.test]
run = "zig build test && bats --jobs 1 test/*.bats"

[tasks.check]
run = "zig fmt --check src/ && zig build check && zig build test && bats --jobs 1 test/*.bats"
